export const MD = 'Master Data'
export const EH = 'Equipment Handling'
export const PR = 'PullOut Request'
export const IS = 'Internal Servicing'
export const PM = 'Preventive Maintenance'
export const CM = 'Corrective Maintenance'

export const A_MD = 'md'
export const A_EH = 'eh'
export const A_PR = 'pullout'
export const A_IS = 'is'
export const A_PM = 'pm'
export const A_CM = 'cm'